### ISSUE TITLE
really boring

### ISSUE THREAD

**Issue by IsaacGHoward** [TylerSCook/spaceship#1]
i expected quality tyler

**Comment by IsaacGHoward** [comment]
terrible game tyler

**Comment by IsaacGHoward** [comment]
what would your parents say tyler

**Comment by TylerSCook** [comment]
:'(

**Comment by IsaacGHoward** [comment]
like what the hell

**Comment by IsaacGHoward** [comment]
srsly

**Comment by Costa6Vincent** [comment]
this code is crap

**Comment by Costa6Vincent** [comment]
awful

**Comment by IsaacGHoward** [comment]
^^

**Comment by IsaacGHoward** [comment]
lol haha its still bad

**Comment by Costa6Vincent** [comment]
Great game, super buggy and not many features. Not to mention that there is no defined objective or point in playing as highscores are not saved. Oh wait there is no score either.

**Comment by TylerSCook** [comment]
:'(
